Hero
front-end-by-rimantas/29a-grupe-elvish-portfolio pull request #28
Opened 2021-07-16 14:34 UTC by KarolisLuko

2021-07-17 08:04 UTC, GedasPupa requested changes
Please change selectors by tag name to class name. More info in discord

2021-07-17 08:04 UTC, GedasPupa commented on css/main.css
> +p{
please, change common  selectors to class names / ids.

2021-07-19 11:07 UTC, vadimsharanov commented on css/main.css
> +p{
Sutinkiu su Gediminu

2021-07-29 10:37 UTC, closed without merging

2021-07-29 10:37 UTC, GedasPupa commented
jau perkelta i developa/masteri