Hire me
front-end-by-rimantas/29a-grupe-elvish-portfolio pull request #34
Opened 2021-07-20 06:04 UTC by MantasDot

2021-07-21 17:36 UTC, GedasPupa requested changes

2021-07-21 17:36 UTC, GedasPupa commented on css/components/hireme.css
> +    height: 40vh;
reikia pritaikyti responsive'ui.

2021-07-22 07:32 UTC, vadimsharanov approved these changes
Looks good.

2021-07-22 07:34 UTC, MantasDot reviewed
done

2021-07-22 07:55 UTC, GedasPupa commented on css/components/hireme.css
> +    height: 40vh;
resolved

2021-07-22 07:56 UTC, GedasPupa approved these changes
nice job!

2021-07-22 07:56 UTC, merged